<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:gco="http://www.isotc211.org/2005/gco" xmlns:gmd="http://www.isotc211.org/2005/gmd"
    xmlns:rw="http://metawal.wallonie.be/schemas/3.0" version="2.0">
    
    <xsl:import href="../iso19139/update-fixed-info.xsl"/>
    
    <xsl:template match="/root" priority="2">
        <xsl:apply-templates select="rw:MD_Metadata"/>
    </xsl:template>
    
    <xsl:template match="rw:MD_Metadata">
        <xsl:copy>
            <xsl:apply-templates select="@*"/>
            <xsl:if test="not(@gco:isoType)">
                <xsl:attribute name="gco:isoType">gmd:MD_Metadata</xsl:attribute>
            </xsl:if>
            
            <gmd:fileIdentifier>
                <gco:CharacterString>
                    <xsl:value-of select="/root/env/uuid"/>
                </gco:CharacterString>
            </gmd:fileIdentifier>
            
            <xsl:apply-templates select="gmd:language"/>
            <xsl:apply-templates select="gmd:characterSet"/>
            
            <xsl:choose>
                <xsl:when test="/root/env/parentUuid!=''">
                    <gmd:parentIdentifier>
                        <gco:CharacterString>
                            <xsl:value-of select="/root/env/parentUuid"/>
                        </gco:CharacterString>
                    </gmd:parentIdentifier>
                </xsl:when>
                <xsl:when test="gmd:parentIdentifier">
                    <xsl:copy-of select="gmd:parentIdentifier"/>
                </xsl:when>
            </xsl:choose>
            <xsl:apply-templates
                select="node()[not(self::gmd:language) and not(self::gmd:characterSet)]"/>
        </xsl:copy>
    </xsl:template>
    
    
    <xsl:template match="rw:MD_Metadata[not(@gco:isoType)]|
        rw:CI_ResponsibleParty[not(@gco:isoType)]|
        rw:LI_Lineage[not(@gco:isoType)]|
        rw:MD_LegalConstraints[not(@gco:isoType)]">
        <xsl:copy>
            <xsl:copy-of select="@*"/>
            <xsl:attribute name="gco:isoType">
                <xsl:value-of select="concat('gmd:', local-name(.))"/>
            </xsl:attribute>
            <xsl:copy-of select="*"/>
        </xsl:copy>
    </xsl:template>
    
    
    <!-- ================================================================= -->
    <!-- Do not process MD_Metadata header generated by previous template  -->
    <xsl:template match="rw:MD_Metadata/gmd:fileIdentifier|rw:MD_Metadata/gmd:parentIdentifier"
        priority="10"/>
    
</xsl:stylesheet>
